# Generated by Django 5.0.4 on 2025-04-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
