# Generated by Django 5.0.4 on 2025-04-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_end_task_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('Task', 'Task'), ('Bug', 'Bug'), ('Feature', 'Feature')], default='Task', max_length=20),
        ),
    ]
